# Generated by Django 3.1.1 on 2020-09-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('TEACHER', 'teacher'), ('STUDENT', 'student')], default='STUDENT', max_length=20, verbose_name='user role'),
        ),
    ]
