# Generated by Django 3.1.1 on 2020-09-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200922_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('TEACHER', 'teacher'), ('STUDENT', 'student')], max_length=20, verbose_name='user role'),
        ),
    ]
