# Generated by Django 3.1.1 on 2020-09-23 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_remove_assignment_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='assignment.assignment'),
        ),
    ]
